### ISSUE TITLE
legendary item "more when lower"

### ISSUE THREAD

**Issue by MasterNO122333** [GCer-Hidenori/MinerGunBuilderCalculator#29]
weird averge damage calculation. changes even with the same set up.
https://user-images.githubusercontent.com/95165287/145721529-8f977f56-33d4-482c-88e9-698fba02c44b.mp4

**Comment by GCer-Hidenori** [comment]
Since the average value of ML cannot be calculated by a mathematical formula, this program make a projectile 1000 times and calculate the average damage.
And this program use random numbers in the Criticalx2 calculation, the result will be different in each calculation.

I'll see if I can't find a better way.
Please give me some time.

**Comment by MasterNO122333** [comment]
ok i understand. that is no problem take the time you need.
